[package]
name = "Rucore_OS"
version = "0.1.0"
authors = ["ivanium <ivanium@126.com>; Gword <xxx@yyy.zzz>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
multiboot2 = "0.1.0"